[browser]
gatherUsageStats = false
 
[theme]
primaryColor = "#29B5E8"
backgroundColor = "#0b1326"
secondaryBackgroundColor = "#131b2e"
textColor = "#F4F7F6"
 
[client]
showErrorDetails = true
toolbarMode = "auto"
showSidebarNavigation = true
 
[logger]
level = "error"