[browser]
gatherUsageStats = false

[client]
showErrorDetails = true
toolbarMode = "minimal"

[logger]
level = "error"

[theme]
primaryColor = "#4070F4"
backgroundColor = "#F4F7F6"
secondaryBackgroundColor = "#E8F0F5"
textColor = "#11101D"
font = "sans serif"
# Valores adicionales para evitar warnings en consola del cliente
widgetBackgroundColor = "#FFFFFF"
widgetBorderColor = "#E6EEF9"
skeletonBackgroundColor = "#F4F7F6"
